config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "home#index"
  get 'home/index'
  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: {:new => ''}
  resources :articles do
    resources :comments, only: [:create]
    member do
      put 'like' => 'articles#upvote'
      put 'dislike' => 'articles#downvote'
    end
  end

end

app/models/article.rb
class Article < ActiveRecord::Base
  acts_as_votable
  has_many :comments
  has_one :user
  validates :title, presence: true
  validates :title, length: { maximum: 140 }
  validates :text, presence: true
  validates :text, length: { maximum: 4000 }

  def subject
    title
  end

  def last_comment
    comments.last
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user

  validates :body, length: { maximum: 4000 }
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  acts_as_voter
  has_many :articles
  has_many :comments

  # Set sizing for images
  has_attached_file :avatar, styles: { small: '20x20', med: '100x100', large: '200x200'}, :default_url => '/images/:style/missing.png'
  # Validate content type
  validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/
  # Validate filename
  validates_attachment_file_name :avatar, matches: [/png\Z/, /jpe?g\Z/]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:username, :email, :password, :current_password, :avatar) }
    devise_parameter_sanitizer.permit(:sign_in) { |u| u.permit(:username, :email, :password, :current_password, :avatar) }
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_filter :authenticate_user!, :except => [:index, :show]
  before_action :find_article, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
  before_action :check_auth, :only => [:edit, :update, :destroy]


  def new
  end

  def create
    @article = Article.new(article_params)
    @article.author = current_user.username

    if @article.valid?
      @article.save
      redirect_to @article
    else
      render action: 'new'
    end

  end

  def show
    @comments = Comment.all
    @post_comments = Comment.where(article_id: 1)

    @comm_auth = Comment.find_or_create_by(author: @article.author)
    @commenter_avatar = User.find_or_create_by(username: @comm_auth.author)
    # username of article author (using for extracting author's avatar)
    @user = User.find_or_create_by(username: @article.author)
  end

  def index
    @articles = Article.order(id: :desc)
    # @article = Article.find(params[:id])
    # @user = User.find_or_create_by(username: @article.author)
  end

  def edit

  end

  def update
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_path
  end

  def upvote
    @article.upvote_from current_user
    redirect_to article_path(@article)
  end

  def downvote
    @article.downvote_from current_user
    redirect_to article_path(@article)
  end

  private
  def article_params
    params.require(:article).permit(:title, :text)
  end

  def find_article
    @article = Article.find(params[:id])
  end

  def check_auth
    if current_user.username != @article.author
      flash[:notice] = 'Sorry, you can\'t edit this post'
      redirect_to root_path
    end
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_filter :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    new_comment = @article.comments.new(comment_params)
    new_comment.author = current_user.username
    new_comment.save

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def new

  end

  def create
    @contact = Contact.new(contact_params)

    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end

  end

  private
  def contact_params
    params.require(:contact).permit(:email, :message)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to articles_path
  end

  def contacts
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms

  end

  def about

  end
end

app/controllers/terms_controller.rb
class TermsController < ApplicationController
  def new
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def url_to_image string
    string.gsub! /\s(https:\/\/.*?)\s/,
                  '<p><img src="\1"/></p>'
    string.html_safe
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/terms_helper.rb
module TermsHelper
end

app/views/articles/create.html.erb
<h1>Article has been added!</h1>

<a href="/articles">Show all articles</a>
<br/>
<%= link_to 'Show all articles!', articles_path %>

app/views/articles/edit.html.erb
<h1>Edit article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
    <p>
      <%= f.label :title%><br/>
      <%= f.text_field :title, class: 'form-control'%>
    </p>
    <p>
      <%= f.label :text%><br/>
      <%= f.text_area :text, class: 'form-control'%>
    </p>
    <p>
      <%= f.submit 'Submit', class: 'btn btn-success' %>
    </p>
<%end%>

app/views/articles/index.html.erb
<div class="row">

  <div class="col-sm-8 blog-main">

    <div class="blog-post">
      <% @articles.each do |a| %>
      <h2 class="blog-post-title"><%= link_to a.title, a %></h2>
      <p class="blog-post-meta">Submitted <%= time_ago_in_words(a.created_at) %> ago by <a href="#"><%= a.author %></a></p>

      <p>        
        <%= a.text %>
      </p>
      <br>
      <p>
          <span class="glyphicon glyphicon-comment" aria-hidden="true" style="margin-right: 0.5em"></span><%= link_to a.comments.size, a %> |
          <!-- Checking for user's priveleges -->
          <% if a.author == current_user.username %>
          <span class="glyphicon glyphicon-edit" aria-hidden="true" style="margin-right: 0.5em; margin-left: 5px;"></span><%= link_to 'Edit', edit_article_path(a) %> |
          <span class="glyphicon glyphicon-remove" aria-hidden="true" style="margin-right: 0.5em"></span><%= link_to 'Delete', a, method: :delete, data: {confirm: 'Delete article?'} %>
          <% end %>
      </p>

          <hr>
      <% end %>


    </div><!-- /.blog-post -->

  </div><!-- /.blog-main -->

  <div class="col-sm-3 col-sm-offset-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
      <h4>About</h4>
      <p>Sometimes there's a hole in the world<em>That I can sneak trough</em> ...</p>
    </div>
    <div class="sidebar-module">
      <h4>Elsewhere</h4>
      <ol class="list-unstyled">
        <li><a href="https://github.com/alexxero">GitHub</a></li>
        <li><a href="#">Twitter</a></li>
        <li><a href="#">Facebook</a></li>
      </ol>
    </div>
  </div><!-- /.blog-sidebar -->

</div><!-- /.row -->

app/views/articles/new.html.erb
<h1>New article</h1>

<%= form_for :article, url: '/articles' do |f| %>
  <p>
    <%= f.label :title%><br/>
    <%= f.text_field :title, class: 'form-control' %>
  </p>
  <p>
    <%= f.label :text%><br/>
    <%= f.text_area :text, class: 'form-control' %>
  </p>
  <p>
    <%= f.submit 'Submit', class: 'btn btn-success', :html => { :style => 'height: 120px' } %>
  </p>
<%end%>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>

<h3>
  <%= @article.text %>
</h3>
<br>
<div class="caption" style="text-align: left;">
  <%= link_to like_article_path(@article), class: 'like', method: :put do %>
      <button type="button" class="btn btn-default" aria-label="Left Align" style="border-color: transparent;">
        <span class="glyphicon glyphicon-thumbs-up glyphicon-align-center" aria-hidden="true" ></span>
        <span class="badge"><%= @article.get_upvotes.size %></span>
      </button>
  <% end  %>

  <%= link_to dislike_article_path(@article), class: 'like', method: :put do %>
      <button type="button" class="btn btn-default" aria-label="Left Align" style="border-color: transparent;">
        <span class="glyphicon glyphicon-thumbs-down glyphicon-align-left" aria-hidden="true" ></span>
        <span class="badge"><%= @article.get_downvotes.size %></span>
      </button>
  <% end  %>
</div>
<br>

<p>
  <%= time_ago_in_words(@article.created_at) %> ago by <b>  <%= image_tag(@user.avatar.url(:small)) %> <%= @article.author %> </b>
</p>

<h4 class="text-muted"> <%= @article.comments.count %> Comments</h4>
<% if user_signed_in? %>
<p>
  <%= form_for([@article, @article.comments.build]) do |f| %>

    <p>
      <%= f.label :body, class: "text-muted" %><br/>
      <%= f.text_area :body, class: "form-control" %>
    </p>
    <p>
      <%= f.submit 'Submit comment', class: "btn btn-success" %>
    </p>
  <% end %>
</p>
<% else %>
    <br>
    <p style="color: yellowgreen; font-weight: 600;"><i>You must be signed in to comment</i></p>
    <br>
<% end %>
<% @article.comments.each do |comm| %>
    <p>
      <b>
        <%= comm.body %>
      </b>
    </p>
    <p>
      <i>
        <%= comm.author %>
      </i>
    </p>
    <p>
      <small>
        <%= comm.created_at %>
      </small>
    </p>
    <br>
<% end %>

app/views/contacts/create.html.erb
<h1>We are appreciate for your feedback!</h1>

app/views/contacts/new.html.erb
<h1><%= t('contacts.contact_us') %></h1>

<%= form_for :contact, url: contacts_path do |f| %>
    <% if @contact && @contact.errors.any? %>

    <p>
       <ul>
        <% @contact.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
       </ul>
    </p>
    <% end %>

    <p>
      <%= f.label :email%><br/>
      <%= f.text_field :email, class: 'form-control' %>
    </p>
    <p>
      <%= f.label :message%><br/>
      <%= f.text_area :message, class: 'form-control' %>
    </p>
    <p>
      <%= f.submit 'Send message', class: 'btn btn-success' %>
    </p>
<%end%>

app/views/home/index.html.erb
<h1>Sign In please</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link data-require="bootstrap-css@3.3.6" data-semver="3.3.6" rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.css" />
  <script data-require="jquery@2.2.0" data-semver="2.2.0" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <nav class="navbar navbar-inverse" role="navigation">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
      </div>

      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">

        <%= link_to "Blog on RoR", articles_path, class: "navbar-brand" %>

        </ul>

        <ul class="nav navbar-nav navbar-right">
          <li>
            <% if user_signed_in? %>
              <li><a href="<%= new_article_path %>">Add new post</a></li>
              <li><a href="<%= edit_user_registration_path %>">Hello, <%= current_user.username %></a></li>
              <li><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
          <% else %>
              <li><%= link_to 'Log In', new_user_session_path %></li>
          <% end %>
          </li>
        </ul>

      </div>

    </nav>
    <% if notice %>
      <div class="notice alert-info" style="padding: 10px 15px; width: max-content; border-radius: 7%; margin: auto;"><%= notice %></div>
    <% elsif alert %>
      <div class="alert alert-warning" style="padding: 10px 15px; width: max-content; border-radius: 7%; margin: auto;"><%= alert %></div>
    <% end %>
    <%= yield %>
  </div>

</body>
<script>
  $(function () {
    $('.notice').fadeOut(5000);
    $('.alert').fadeOut(5000);
  })
</script>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>

app/views/pages/terms.html.erb
<h2>Terms</h2>

app/views/terms/new.html.erb
<h1>Terms</h1>